# main.tf — Relational Database capability
#
# WHAT THIS GIVES A CONSUMING TEAM:
#   - A DB subnet group correctly scoped to private subnets
#   - A security group that only allows traffic from specified SGs
#     (never a raw "open to VPC" or "open to internet")
#   - Encryption at rest, enforced
#   - An auto-generated password, stored in Secrets Manager -- never
#     typed by a human, never in state as plain input, never in git
#   - Environment-appropriate backup/Multi-AZ defaults
#   - Consistent naming/tagging
#
# SECURITY NOTE (worth restating in your docs/ADRs): the password is
# generated by Terraform's random_password resource and immediately
# written to Secrets Manager. It DOES exist in Terraform state (this
# is unavoidable -- Terraform must know the value to set it on the DB).
# This means your state file itself must be treated as sensitive,
# which is exactly why bootstrap/main.tf enabled S3 encryption on the
# state bucket -- that decision and this one are connected.

locals {
  name_prefix = "${var.project}-${var.environment}-${var.db_purpose}"

  common_tags = {
    Project     = var.project
    Environment = var.environment
    Owner       = var.owner_team
    ManagedBy   = "terraform"
    Platform    = "cob"
    Purpose     = var.db_purpose
  }
}

resource "aws_db_subnet_group" "this" {
  name       = "${local.name_prefix}-subnet-group"
  subnet_ids = var.private_subnet_ids

  tags = local.common_tags
}

resource "aws_security_group" "db" {
  name        = "${local.name_prefix}-sg"
  description = "Allows DB access only from explicitly listed security groups"
  vpc_id      = var.vpc_id

  egress {
    description = "Allow all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = local.common_tags
}

# One ingress rule per allowed security group -- deliberately NOT a
# single rule with a list of CIDRs. This keeps "who can reach the DB"
# self-documenting in the AWS console: each rule's source IS a specific,
# named security group, not an opaque IP range.
resource "aws_security_group_rule" "db_ingress" {
  count = length(var.allowed_security_group_ids)

  type                     = "ingress"
  from_port                = local.db_port
  to_port                  = local.db_port
  protocol                 = "tcp"
  security_group_id        = aws_security_group.db.id
  source_security_group_id = var.allowed_security_group_ids[count.index]
  description               = "DB access from allowed security group"
}

locals {
  db_port = var.engine == "postgres" ? 5432 : 3306
}

resource "random_password" "master" {
  length  = 24
  special = true
  # Exclude characters that commonly cause escaping issues in
  # connection strings / shell contexts.
  override_special = "!#$%^&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "db_credentials" {
  name = "${local.name_prefix}-db-credentials"

  tags = local.common_tags
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id
  secret_string = jsonencode({
    username = var.master_username
    password = random_password.master.result
    engine   = var.engine
    host     = aws_db_instance.this.address
    port     = local.db_port
    dbname   = var.db_name
  })
}

resource "aws_db_instance" "this" {
  identifier     = "${local.name_prefix}-db"
  engine         = var.engine
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage_gb
  storage_encrypted     = true

  db_name  = var.db_name
  username = var.master_username
  password = random_password.master.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.db.id]

  multi_az                = var.multi_az
  backup_retention_period = var.backup_retention_days

  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${local.name_prefix}-final-snapshot"

  tags = local.common_tags
}
